# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - prod-ap-wolds-hr-node-js-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Clean and build
        run: |
          echo "üßπ Cleaning dist/"
          rm -rf dist
          npm ci
          npm run build

      - name: Verify dist contents
        run: |
          echo "üìÅ dist folder structure:"
          ls -R dist
          echo "üîç Check dist/server.js:"
          head -n 20 dist/server.js
          
      - name: Zip artifact for deployment
        run: |
          echo "üì¶ Creating clean release.zip"
          mkdir package
          cp -r dist package/
          cp package.json package-lock.json package/
          cd package
          zip -r ../release.zip .

      - name: Check zip contents
        run: unzip -l release.zip
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wolds-hr-fe-node-js'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2013966326404813B2C6F103209BCC5D }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prod-ap-wolds-hr-node-js-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2013966326404813B2C6F103209BCC5D }}
